version: '3.6'
# User default database -> postgres
services:
  
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"

  web:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:docker@db:5432/braum_db
      - ALLOWED_HOSTS=localhost
      - DEBUG=1
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db